ACTIVITIES = [
    {"id": 1, "name": "Morning Walk", "description": "A gentle walk to start the day.", "duration": 2, "physicality": 2, "sociability": 1, "importance": 4},
    {"id": 2, "name": "Morning Jog", "description": "A refreshing solo run.", "duration": 2, "physicality": 4, "sociability": 1, "importance": 4},
    {"id": 3, "name": "Stretching", "description": "A short full-body stretch routine.", "duration": 1, "physicality": 2, "sociability": 1, "importance": 4},
    {"id": 4, "name": "Yoga", "description": "Gentle movement and breathwork.", "duration": 2, "physicality": 3, "sociability": 1, "importance": 4},
    {"id": 5, "name": "Meditation", "description": "Mindful breathing and stillness.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 5},
    {"id": 6, "name": "Bodyweight Workout", "description": "Push-ups, squats, and core work.", "duration": 2, "physicality": 4, "sociability": 1, "importance": 4},
    {"id": 7, "name": "Weight Lifting", "description": "Strength training at home or gym.", "duration": 3, "physicality": 5, "sociability": 2, "importance": 4},
    {"id": 8, "name": "Cycling", "description": "A ride around your neighborhood or park.", "duration": 3, "physicality": 4, "sociability": 2, "importance": 3},
    {"id": 9, "name": "Swimming", "description": "Laps or light swimming session.", "duration": 3, "physicality": 4, "sociability": 2, "importance": 4},
    {"id": 10, "name": "Dance Practice", "description": "Practice dance moves or routines.", "duration": 2, "physicality": 3, "sociability": 2, "importance": 3},
    {"id": 11, "name": "Play Football", "description": "Kickabout or casual football game.", "duration": 3, "physicality": 5, "sociability": 4, "importance": 3},
    {"id": 12, "name": "Play Basketball", "description": "Shoot hoops or join a casual game.", "duration": 3, "physicality": 5, "sociability": 4, "importance": 3},
    {"id": 13, "name": "Tennis Session", "description": "Practice serves and rallies.", "duration": 3, "physicality": 4, "sociability": 3, "importance": 3},
    {"id": 14, "name": "Badminton", "description": "A quick indoor or outdoor game.", "duration": 2, "physicality": 4, "sociability": 3, "importance": 3},
    {"id": 15, "name": "Hiking", "description": "Go on a local trail walk.", "duration": 4, "physicality": 4, "sociability": 2, "importance": 3},
    {"id": 16, "name": "Home Mobility Routine", "description": "Joint mobility and posture work.", "duration": 1, "physicality": 2, "sociability": 1, "importance": 4},
    {"id": 17, "name": "Foam Rolling", "description": "Muscle recovery and tension relief.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 3},
    {"id": 18, "name": "Take the Stairs", "description": "Choose stairs for extra movement.", "duration": 1, "physicality": 3, "sociability": 1, "importance": 3},
    {"id": 19, "name": "Read a Book", "description": "Read a chapter from a book.", "duration": 2, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 20, "name": "Studying", "description": "Focused study session for classes or exams.", "duration": 3, "physicality": 1, "sociability": 1, "importance": 5},
    {"id": 21, "name": "Review Lecture Notes", "description": "Go over key points from recent lectures.", "duration": 2, "physicality": 1, "sociability": 1, "importance": 5},
    {"id": 22, "name": "Practice Past Papers", "description": "Solve timed questions from past exams.", "duration": 3, "physicality": 1, "sociability": 1, "importance": 5},
    {"id": 23, "name": "Flashcard Revision", "description": "Revise key facts using flashcards.", "duration": 2, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 24, "name": "Write Assignment Draft", "description": "Work on coursework writing.", "duration": 3, "physicality": 1, "sociability": 1, "importance": 5},
    {"id": 25, "name": "Coding Practice", "description": "Solve coding exercises or build a feature.", "duration": 3, "physicality": 1, "sociability": 1, "importance": 5},
    {"id": 26, "name": "Learn a New Topic", "description": "Explore a topic beyond your syllabus.", "duration": 2, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 27, "name": "Language Learning", "description": "Practice vocabulary and speaking basics.", "duration": 2, "physicality": 1, "sociability": 2, "importance": 4},
    {"id": 28, "name": "Attend Office Hours", "description": "Ask questions and clarify difficult concepts.", "duration": 2, "physicality": 1, "sociability": 3, "importance": 4},
    {"id": 29, "name": "Group Study Session", "description": "Collaborate with classmates on revision.", "duration": 3, "physicality": 1, "sociability": 4, "importance": 4},
    {"id": 30, "name": "Plan Weekly Study Goals", "description": "Set targets for the coming week.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 31, "name": "Deep Work Session", "description": "Uninterrupted focus block for key tasks.", "duration": 3, "physicality": 1, "sociability": 1, "importance": 5},
    {"id": 32, "name": "Inbox Zero", "description": "Clear and organize your emails.", "duration": 1, "physicality": 1, "sociability": 2, "importance": 3},
    {"id": 33, "name": "Plan Tomorrow", "description": "Create a realistic plan for the next day.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 34, "name": "Time Blocking", "description": "Schedule tasks into calendar blocks.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 35, "name": "Resume Update", "description": "Refresh achievements and skills on your CV.", "duration": 2, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 36, "name": "Portfolio Work", "description": "Improve personal projects for your portfolio.", "duration": 3, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 37, "name": "Networking Message", "description": "Reach out to a professional contact.", "duration": 1, "physicality": 1, "sociability": 3, "importance": 3},
    {"id": 38, "name": "Mock Interview Prep", "description": "Practice common interview questions.", "duration": 2, "physicality": 1, "sociability": 2, "importance": 4},
    {"id": 39, "name": "Skill Course Module", "description": "Complete one module of an online course.", "duration": 2, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 40, "name": "Budget Check", "description": "Review spending and plan upcoming costs.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 41, "name": "Meal Prep", "description": "Prepare meals for the next few days.", "duration": 3, "physicality": 2, "sociability": 1, "importance": 4},
    {"id": 42, "name": "Cook Dinner", "description": "Prepare a healthy home-cooked meal.", "duration": 2, "physicality": 2, "sociability": 2, "importance": 4},
    {"id": 43, "name": "Hydration Check", "description": "Track and improve water intake.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 44, "name": "Take Vitamins", "description": "Keep up with daily supplements.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 3},
    {"id": 45, "name": "Sleep Routine", "description": "Wind down and prepare for quality sleep.", "duration": 2, "physicality": 1, "sociability": 1, "importance": 5},
    {"id": 46, "name": "Mindful Breathing Break", "description": "A short breathing reset.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 47, "name": "Journal Reflection", "description": "Write thoughts and daily reflections.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 48, "name": "Gratitude List", "description": "Note a few things you appreciate today.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 3},
    {"id": 49, "name": "Digital Detox", "description": "Take a break from social media and screens.", "duration": 2, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 50, "name": "Nature Break", "description": "Spend quiet time outdoors.", "duration": 2, "physicality": 2, "sociability": 1, "importance": 3},
    {"id": 51, "name": "Tidy Desk", "description": "Declutter your workspace.", "duration": 1, "physicality": 2, "sociability": 1, "importance": 3},
    {"id": 52, "name": "Room Cleaning", "description": "Clean and organize your room.", "duration": 2, "physicality": 3, "sociability": 1, "importance": 4},
    {"id": 53, "name": "Laundry", "description": "Wash, dry, and fold clothes.", "duration": 2, "physicality": 2, "sociability": 1, "importance": 4},
    {"id": 54, "name": "Do the Dishes", "description": "Clean kitchen dishes and surfaces.", "duration": 1, "physicality": 2, "sociability": 1, "importance": 3},
    {"id": 55, "name": "Grocery Shopping", "description": "Buy essentials and healthy food.", "duration": 2, "physicality": 2, "sociability": 2, "importance": 4},
    {"id": 56, "name": "Declutter One Area", "description": "Organize one shelf, drawer, or corner.", "duration": 1, "physicality": 2, "sociability": 1, "importance": 3},
    {"id": 57, "name": "Pay Bills", "description": "Handle routine financial admin tasks.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 5},
    {"id": 58, "name": "Update Calendar", "description": "Add deadlines and appointments.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 59, "name": "Backup Files", "description": "Secure important files and documents.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 60, "name": "Organize Notes", "description": "Sort class notes and resources.", "duration": 2, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 61, "name": "Call Family", "description": "Check in with a family member.", "duration": 1, "physicality": 1, "sociability": 4, "importance": 4},
    {"id": 62, "name": "Call a Friend", "description": "Catch up with a friend.", "duration": 1, "physicality": 1, "sociability": 4, "importance": 3},
    {"id": 63, "name": "Have Coffee with a Friend", "description": "Meet someone for a short catch-up.", "duration": 2, "physicality": 1, "sociability": 5, "importance": 3},
    {"id": 64, "name": "Join a Study Group", "description": "Collaborative revision with peers.", "duration": 3, "physicality": 1, "sociability": 4, "importance": 4},
    {"id": 65, "name": "Attend a Club Meeting", "description": "Participate in a society or club session.", "duration": 2, "physicality": 1, "sociability": 4, "importance": 3},
    {"id": 66, "name": "Team Project Meeting", "description": "Coordinate tasks with teammates.", "duration": 2, "physicality": 1, "sociability": 4, "importance": 4},
    {"id": 67, "name": "Board Games", "description": "Play social games with friends.", "duration": 3, "physicality": 1, "sociability": 5, "importance": 2},
    {"id": 68, "name": "Movie Night", "description": "Watch a movie with others.", "duration": 3, "physicality": 1, "sociability": 3, "importance": 2},
    {"id": 69, "name": "Walk and Talk", "description": "Go for a walk while catching up.", "duration": 2, "physicality": 2, "sociability": 4, "importance": 3},
    {"id": 70, "name": "Volunteer Work", "description": "Help with a local volunteer activity.", "duration": 3, "physicality": 2, "sociability": 4, "importance": 5},
    {"id": 71, "name": "Listen to a Podcast", "description": "Learn or relax with a podcast episode.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 2},
    {"id": 72, "name": "Listen to Music", "description": "Take a music break.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 2},
    {"id": 73, "name": "Practice an Instrument", "description": "Instrument practice session.", "duration": 2, "physicality": 1, "sociability": 1, "importance": 3},
    {"id": 74, "name": "Sketch or Draw", "description": "Create a quick sketch or drawing.", "duration": 2, "physicality": 1, "sociability": 1, "importance": 3},
    {"id": 75, "name": "Photography Walk", "description": "Take photos while walking around.", "duration": 2, "physicality": 2, "sociability": 1, "importance": 2},
    {"id": 76, "name": "Creative Writing", "description": "Write a story, poem, or short piece.", "duration": 2, "physicality": 1, "sociability": 1, "importance": 3},
    {"id": 77, "name": "Read News Summary", "description": "Catch up on key world news.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 3},
    {"id": 78, "name": "Watch Educational Video", "description": "Learn from a short educational video.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 3},
    {"id": 79, "name": "Solve a Puzzle", "description": "Complete a crossword or logic puzzle.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 2},
    {"id": 80, "name": "Play Chess", "description": "Play a casual chess game.", "duration": 2, "physicality": 1, "sociability": 2, "importance": 3},
    {"id": 81, "name": "Garden Care", "description": "Water plants or do light garden upkeep.", "duration": 1, "physicality": 2, "sociability": 1, "importance": 3},
    {"id": 82, "name": "Plan Weekly Meals", "description": "Organize meals for the week.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 83, "name": "Prepare Lunch", "description": "Make a balanced lunch.", "duration": 1, "physicality": 2, "sociability": 1, "importance": 4},
    {"id": 84, "name": "Go to Bed on Time", "description": "Stick to your planned bedtime.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 5},
    {"id": 85, "name": "Take a Power Nap", "description": "Short restorative nap.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 3},
    {"id": 86, "name": "Screen-Free Hour", "description": "Spend one hour away from screens.", "duration": 2, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 87, "name": "Posture Check", "description": "Do a quick posture and ergonomics reset.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 3},
    {"id": 88, "name": "Self-Care Routine", "description": "Personal care and reset routine.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 4},
    {"id": 89, "name": "Errand Run", "description": "Complete one practical errand.", "duration": 2, "physicality": 2, "sociability": 2, "importance": 3},
    {"id": 90, "name": "Weekly Reflection", "description": "Review wins, setbacks, and next steps.", "duration": 1, "physicality": 1, "sociability": 1, "importance": 4},
]
