ACTIVITIES = [
    {"id": 1,  "name": "Morning Jog",        "description": "A refreshing solo run to start the day.",                  "duration": 2, "physicality": 4, "sociability": 1, "importance": 4},
    {"id": 2,  "name": "Reading",             "description": "Quiet time with a good book.",                             "duration": 1, "physicality": 1, "sociability": 1, "importance": 3},
    {"id": 3,  "name": "Team Basketball",     "description": "Fast-paced team sport at the local court.",                "duration": 3, "physicality": 5, "sociability": 5, "importance": 3},
    {"id": 4,  "name": "Meditation",          "description": "Mindful breathing and stillness practice.",                "duration": 1, "physicality": 1, "sociability": 1, "importance": 5},
    {"id": 5,  "name": "Cook a New Recipe",   "description": "Try a cuisine you haven't made before.",                  "duration": 3, "physicality": 2, "sociability": 2, "importance": 4},
    {"id": 6,  "name": "Call a Friend",       "description": "Catch up with someone you've been meaning to contact.",    "duration": 1, "physicality": 1, "sociability": 4, "importance": 3},
    {"id": 7,  "name": "Weight lifting",      "description": "A full workout at the gym focused on weights.",            "duration": 3, "physicality": 5, "sociability": 2, "importance": 4},
    {"id": 8,  "name": "Board Game Night",    "description": "A fun evening of strategy games with others.",             "duration": 4, "physicality": 1, "sociability": 5, "importance": 2},
    {"id": 9,  "name": "Yoga",                "description": "Gentle stretching and breathwork session.",                "duration": 2, "physicality": 3, "sociability": 1, "importance": 3},
    {"id": 10, "name": "Cycling",             "description": "A lengthy scenic bike ride around the city.",              "duration": 3, "physicality": 4, "sociability": 2, "importance": 3},
    {"id": 11, "name": "Journaling",          "description": "Reflect on your thoughts and goals in writing.",           "duration": 1, "physicality": 1, "sociability": 1, "importance": 3},
    {"id": 12, "name": "Snorkelling",         "description": "Explore marine life in coastal waters.",                   "duration": 5, "physicality": 3, "sociability": 2, "importance": 3},
    {"id": 13, "name": "Volunteer Work",      "description": "Give back to the community through local volunteering.",   "duration": 5, "physicality": 3, "sociability": 4, "importance": 5},
    {"id": 14, "name": "Group Hike",          "description": "Explore nature trails with a group of friends.",           "duration": 4, "physicality": 4, "sociability": 4, "importance": 3},
    {"id": 15, "name": "Pottery Class",       "description": "Learn the basics of throwing clay on a wheel.",            "duration": 3, "physicality": 2, "sociability": 3, "importance": 2},
    {"id": 16, "name": "Learn a Language",    "description": "Practice conversational skills in a new language.",        "duration": 1, "physicality": 1, "sociability": 2, "importance": 4},
    {"id": 17, "name": "Paint or Draw",       "description": "Express your creative side on canvas or paper.",           "duration": 2, "physicality": 1, "sociability": 1, "importance": 3},
    {"id": 18, "name": "Rock Climbing",       "description": "Indoor or outdoor rock wall climbing.",                    "duration": 4, "physicality": 5, "sociability": 3, "importance": 4},
]
